[package]
name = "app"
version = "0.1.0"
edition = "2021"
rust-version = "1.84"
resolver = "2"

[dependencies]
pollster = { version = "0.4", features = ["macro"] }

crossbeam-channel.workspace = true
wgpu.workspace = true
winit.workspace = true
ffmpeg-next.workspace = true
log.workspace = true
env_logger.workspace = true

transport = { path = "../transport" }
render = { path = "../render" }
clip = { path = "../clip" }
